package com.collincorp.houserental.domain;

public enum NotificationType {
    QUEUE_POSITION,
    PROMOTION,
    CONFIRMATION_DEADLINE,
    RESERVATION_ACCEPTED,
    RESERVATION_CANCELLED,
    REVIEW_REQUEST,
    REVIEW_SUBMITTED,
    LANDLORD_REQUEST_UPDATE,
    PROPERTY_APPROVED,
    GENERAL
}
